version: 2

test: &test
  working_directory: /go/src/github.com/iwannay/gcfg
  steps:
    - checkout
    - run: go version
    - run: go env
    - run: go get -v -t ./...
    - run: go test -v ./...

jobs:
  rc:
    <<: *test
    docker:
      - image: circleci/golang:rc
  go1.14:
    <<: *test
    docker:
      - image: circleci/golang:1.14
  go1.13:
    <<: *test
    docker:
      - image: circleci/golang:1.13


workflows:
  version: 2
  test:
    jobs:
      - rc
      - go1.14
      - go1.13
